<a href="https://colab.research.google.com/github/rkukjk/Traffic-Sign-Classification-and-Recognition-/blob/main/trafficSignClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

We first have to load the image dataset (train and test both)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!unzip '/content/drive/My Drive/trafficData.zip'

Streaming output truncated to the last 5000 lines.
  inflating: trafficData/train_dataset/train/M4/00700.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._00700.jpg  
  inflating: trafficData/train_dataset/train/M4/02117.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._02117.jpg  
  inflating: trafficData/train_dataset/train/M4/03209.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._03209.jpg  
  inflating: trafficData/train_dataset/train/M4/02498.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._02498.jpg  
  inflating: trafficData/train_dataset/train/M4/01191.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._01191.jpg  
  inflating: trafficData/train_dataset/train/M4/01185.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._01185.jpg  
  inflating: trafficData/train_dataset/train/M4/01813.jpg  
  inflating: __MACOSX/trafficData/train_dataset/train/M4/._01813.jpg  
  inflating: trafficData/train_d

The next step is to somehow use pandas to get the train.json file into a dataframe.

In [3]:
import pandas as pd

trainLabelsDf = pd.read_json("/content/trafficData/train_dataset/train.json")

In [4]:
trainLabelsDf

annotations
0        {'filename': 'train/W1/00082.jpg', 'label': 9}
1        {'filename': 'train/W1/00021.jpg', 'label': 9}
2        {'filename': 'train/W1/00135.jpg', 'label': 9}
3        {'filename': 'train/W1/00149.jpg', 'label': 9}
4        {'filename': 'train/W1/00008.jpg', 'label': 9}
...                                                 ...
6019  {'filename': 'train/GuideSign/01172.jpg', 'lab...
6020  {'filename': 'train/GuideSign/00361.jpg', 'lab...
6021  {'filename': 'train/GuideSign/00155.jpg', 'lab...
6022  {'filename': 'train/GuideSign/00535.jpg', 'lab...
6023  {'filename': 'train/GuideSign/00089.jpg', 'lab...

[6024 rows x 1 columns]

In [5]:
firstDict = trainLabelsDf.iloc[0]

In [6]:
firstDict = dict(firstDict)

In [7]:
firstDict['annotations']['filename']

'train/W1/00082.jpg'

In [8]:
import matplotlib.pyplot as plt
%matplotlib inline


image1 = plt.imread("/content/trafficData/train_dataset/train/W1/00001.jpg")

In [9]:
image1.shape

(224, 224, 3)

In [10]:
trainDf = pd.DataFrame()

In [11]:
trainDf['image'] = []
trainDf['label'] = []

In [12]:
trainLabelsDf.shape[0]

6024

We will try to grayscale all the images. My motivations for grayscaling images is due to this abstract:



Abstract: There is a common tendency in object recognition research to accumulate large volumes of image features to improve performance. ... Experimental results showed that classification with grayscale images resulted in higher accuracy classification than with RGB images across the different types of classifiers.

In [13]:
from keras.preprocessing import image
import numpy as np 
imageList = []
labelList = []

sizeSet = set()

for i in range(trainLabelsDf.shape[0]):
  annotationDict = trainLabelsDf.iloc[i]
  annotationDict = dict(annotationDict)
  imageString = annotationDict['annotations']['filename']
  imageString = "/content/trafficData/train_dataset/" + imageString
  img = image.load_img(imageString)
  img = image.img_to_array(img)
  sizeSet.add(img.shape[0] * img.shape[1])
  #img = np.mean(img, axis=2)
  img = img.flatten()
  img = img/255
  imageList.append(img)
  currentLabel = annotationDict['annotations']['label']
  labelList.append(currentLabel)


  


In [14]:
imageList[0].shape

(150528,)

In [15]:
sizeSet

{50176}

In [16]:
imageList

[array([0.24705882, 0.26666668, 0.18039216, ..., 0.2       , 0.22745098,
        0.16470589], dtype=float32),
 array([0.54901963, 0.5372549 , 0.4627451 , ..., 0.24313726, 0.2509804 ,
        0.16862746], dtype=float32),
 array([0.6313726 , 0.68235296, 0.7058824 , ..., 0.24705882, 0.27058825,
        0.23137255], dtype=float32),
 array([0.21176471, 0.2509804 , 0.15686275, ..., 0.3019608 , 0.27058825,
        0.02352941], dtype=float32),
 array([0.23529412, 0.25882354, 0.1254902 , ..., 0.2       , 0.21176471,
        0.09803922], dtype=float32),
 array([0.06666667, 0.11764706, 0.07843138, ..., 0.03137255, 0.14901961,
        0.        ], dtype=float32),
 array([0.8980392 , 1.        , 1.        , ..., 0.8627451 , 0.95686275,
        0.99607843], dtype=float32),
 array([0.18039216, 0.21568628, 0.19607843, ..., 0.49803922, 0.56078434,
        0.50980395], dtype=float32),
 array([0.1764706 , 0.20784314, 0.05490196, ..., 0.23921569, 0.22352941,
        0.11764706], dtype=float32),
 array([0.

In [17]:
len(imageList)

6024

In [18]:
len(labelList)

6024

In [19]:
trainDf = pd.DataFrame()

trainDf['image'] = imageList
trainDf['label'] = labelList

In [20]:
trainDf.head(3)

image  label
0  [0.24705882, 0.26666668, 0.18039216, 0.2470588...      9
1  [0.54901963, 0.5372549, 0.4627451, 0.54901963,...      9
2  [0.6313726, 0.68235296, 0.7058824, 0.6313726, ...      9

Trying out the process of how to grayscale an image





In [102]:
plt.matshow(trainDf.iloc[0][0]) # now the image is in grayscale

ValueError: ignored

In [21]:
trainDf.iloc[0][0]

array([0.24705882, 0.26666668, 0.18039216, ..., 0.2       , 0.22745098,
       0.16470589], dtype=float32)

In [22]:
firstImage = trainDf.iloc[0][0]
firstImage.shape

(150528,)

In [23]:
firstImageFlattened = firstImage.flatten() #essentially we are converting a 2D array into a 1D array

In [24]:
firstImageFlattened

array([0.24705882, 0.26666668, 0.18039216, ..., 0.2       , 0.22745098,
       0.16470589], dtype=float32)

In [25]:
firstImageFlattened.shape

(150528,)

In [26]:
import matplotlib.pyplot as plt
import seaborn as sns

import keras
from keras.models import Sequential
from keras.layers import Dense, Conv2D , MaxPool2D , Flatten , Dropout 
from keras.preprocessing.image import ImageDataGenerator
#from keras.optimizers import Adam

from sklearn.metrics import classification_report,confusion_matrix

import tensorflow as tf

import cv2
import os

import numpy as np

In [70]:
# model = keras.Sequential([
#         keras.layers.Dense(100, input_shape=(50176,), activation="relu"),
#         keras.layers.Dense(10, activation="relu")
# ])

# model.compile(optimizer="adam", 
#               loss = "sparse_categorical_crossentropy",
#               metrics = ["accuracy"]
#               )


# model.fit(imageList,labelList, epochs=5)

In [27]:
import numpy as np 
imageList = np.array(imageList)
labelList = np.array(labelList)

In [29]:
model = keras.Sequential([
        keras.layers.Dense(200, input_shape=(150528,), activation="sigmoid"),
        keras.layers.Dense(500, activation="relu"),
        keras.layers.Dense(400, activation="sigmoid"),
        keras.layers.Dense(300, activation="relu"),
        keras.layers.Dense(200, activation="tanh"),
        keras.layers.Dense(100, activation="relu"),
        keras.layers.Dense(75, activation="relu"),
        keras.layers.Dense(50, activation="tanh"),
        keras.layers.Dense(25, activation="relu"),
        keras.layers.Dense(10, activation="sigmoid")
])

model.compile(optimizer="SGD", 
              loss = "sparse_categorical_crossentropy",
              metrics = ["accuracy"],
              )


model.fit(imageList,labelList, epochs=50)

Epoch 1/50
189/189 [==============================] - 23s 120ms/step - loss: 1.5520 - accuracy: 0.5282
Epoch 2/50
189/189 [==============================] - 23s 120ms/step - loss: 1.3612 - accuracy: 0.5669
Epoch 3/50
189/189 [==============================] - 23s 120ms/step - loss: 1.2061 - accuracy: 0.6213
Epoch 4/50
189/189 [==============================] - 23s 121ms/step - loss: 1.1125 - accuracy: 0.6340
Epoch 5/50
189/189 [==============================] - 23s 121ms/step - loss: 0.9958 - accuracy: 0.6766
Epoch 6/50
189/189 [==============================] - 23s 121ms/step - loss: 0.9113 - accuracy: 0.7188
Epoch 7/50
189/189 [==============================] - 23s 121ms/step - loss: 0.8448 - accuracy: 0.7394
Epoch 8/50
189/189 [==============================] - 23s 121ms/step - loss: 0.7583 - accuracy: 0.7580
Epoch 9/50
189/189 [==============================] - 23s 121ms/step - loss: 0.6990 - accuracy: 0.7802
Epoch 10/50
189/189 [==============================] - 23s 121ms/step - l

In [30]:
sizeSet = set()

for i in range(len(imageList)):
  sizeSet.add(imageList[i].shape[0])

In [34]:
sizeSet #checking to see if all the 1D array have same length

{50176}

In [31]:
trainLabelsDf

annotations
0        {'filename': 'train/W1/00082.jpg', 'label': 9}
1        {'filename': 'train/W1/00021.jpg', 'label': 9}
2        {'filename': 'train/W1/00135.jpg', 'label': 9}
3        {'filename': 'train/W1/00149.jpg', 'label': 9}
4        {'filename': 'train/W1/00008.jpg', 'label': 9}
...                                                 ...
6019  {'filename': 'train/GuideSign/01172.jpg', 'lab...
6020  {'filename': 'train/GuideSign/00361.jpg', 'lab...
6021  {'filename': 'train/GuideSign/00155.jpg', 'lab...
6022  {'filename': 'train/GuideSign/00535.jpg', 'lab...
6023  {'filename': 'train/GuideSign/00089.jpg', 'lab...

[6024 rows x 1 columns]

In [34]:
testImage = image.load_img("/content/trafficData/test_dataset/test/W1/00020.jpg")
testImage = image.img_to_array(testImage)
testImage = testImage.flatten()
testImage = testImage/255

testImage.shape

(150528,)

In [41]:
import os
testImageList = []

directory = "/content/trafficData/test_dataset/test/W1"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
    else:
        continue

In [45]:
testImageList = np.array(testImageList)
model.predict(testImageList)

array([[0.23659459, 0.2581659 , 0.751791  , 0.02288207, 0.00550127,
        0.83177036, 0.70539755, 0.9114466 , 0.12500688, 0.99923575],
       [0.3238667 , 0.17037466, 0.71784073, 0.02715823, 0.00573072,
        0.7439021 , 0.57536596, 0.95208055, 0.16373688, 0.9992209 ],
       [0.27922428, 0.2174102 , 0.74350643, 0.02476674, 0.00538582,
        0.80951434, 0.63331974, 0.93066883, 0.13804218, 0.99928725],
       [0.3848455 , 0.3677234 , 0.857573  , 0.02203834, 0.00451636,
        0.92363405, 0.5933196 , 0.83124936, 0.09499955, 0.99875   ],
       [0.3905204 , 0.2500347 , 0.7995287 , 0.0254046 , 0.00489977,
        0.8638522 , 0.52942073, 0.90857553, 0.12478325, 0.998941  ],
       [0.22724438, 0.20559293, 0.7179042 , 0.02442735, 0.00550696,
        0.7986889 , 0.68057823, 0.93657446, 0.14361519, 0.99931014],
       [0.26392984, 0.36020237, 0.8024068 , 0.02313516, 0.00458556,
        0.9230933 , 0.65277797, 0.8414357 , 0.0947465 , 0.9989115 ],
       [0.2894075 , 0.2719566 , 0.7914629

In [47]:
y_predicted = model.predict(testImageList)

In [48]:
np.argmax(y_predicted[0])

9

In [49]:
y_predicted_labels = [np.argmax(i) for i in y_predicted]

In [50]:
y_predicted_labels #this correctly predicts all the W1 signs

[9, 9, 9, 9, 9, 9, 9, 9]

Next we have to figure out a way to get classification report (and evaluate model accuracy using test data)

In [51]:
trainLabelsDf

annotations
0        {'filename': 'train/W1/00082.jpg', 'label': 9}
1        {'filename': 'train/W1/00021.jpg', 'label': 9}
2        {'filename': 'train/W1/00135.jpg', 'label': 9}
3        {'filename': 'train/W1/00149.jpg', 'label': 9}
4        {'filename': 'train/W1/00008.jpg', 'label': 9}
...                                                 ...
6019  {'filename': 'train/GuideSign/01172.jpg', 'lab...
6020  {'filename': 'train/GuideSign/00361.jpg', 'lab...
6021  {'filename': 'train/GuideSign/00155.jpg', 'lab...
6022  {'filename': 'train/GuideSign/00535.jpg', 'lab...
6023  {'filename': 'train/GuideSign/00089.jpg', 'lab...

[6024 rows x 1 columns]

In [52]:
import os
testImageList = []
testLabelList = []

directory = "/content/trafficData/test_dataset/test/GuideSign"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(0)
        
    else:
        continue

directory = "/content/trafficData/test_dataset/test/M1"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(1)
        
    else:
        continue

directory = "/content/trafficData/test_dataset/test/M4"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(2)
        
    else:
        continue


directory = "/content/trafficData/test_dataset/test/M5"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(3)
        
    else:
        continue



directory = "/content/trafficData/test_dataset/test/M6"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(4)
        
    else:
        continue


directory = "/content/trafficData/test_dataset/test/M7"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(5)
        
    else:
        continue


directory = "/content/trafficData/test_dataset/test/P1"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(6)
        
    else:
        continue



directory = "/content/trafficData/test_dataset/test/P10_50"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(7)
        
    else:
        continue


directory = "/content/trafficData/test_dataset/test/P12"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(8)
        
    else:
        continue



directory = "/content/trafficData/test_dataset/test/W1"
for filename in os.listdir(directory):
    # print("h")
    if filename.endswith(".jpg") or filename.endswith(".png"):
        img = str(os.path.join(directory, filename))
        testImage = image.load_img(img)
        testImage = image.img_to_array(testImage)
        testImage = testImage.flatten()
        testImage = testImage/255
        testImageList.append(testImage)
        testLabelList.append(9)
        
    else:
        continue

In [54]:
testImageList = np.array(testImageList)

In [55]:
y_predicted = model.predict(testImageList)

In [56]:
y_predicted_labels = [np.argmax(i) for i in y_predicted]

In [57]:
testLabelList

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,


In [58]:
len(testLabelList)

324

In [59]:
len(y_predicted_labels)

324

In [60]:
counter = 0
for i in y_predicted_labels:
  if (y_predicted_labels[i] == testLabelList[i]):
    counter += 1

  

In [61]:
counter/(len(testLabelList))

0.8425925925925926

In [63]:
from sklearn.metrics import accuracy_score
accuracy_score(testLabelList, y_predicted_labels)

0.9135802469135802

In [68]:
target_names = ['class 0', 'class 1', 'class 2','class 3','class 4','class 5','class 6','class 7','class 8','class 9']
print(classification_report(testLabelList, y_predicted_labels, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.88      0.94      0.91        62
     class 1       0.69      0.79      0.73        14
     class 2       0.96      0.95      0.96       169
     class 3       1.00      0.58      0.74        12
     class 4       0.60      0.38      0.46         8
     class 5       0.88      0.92      0.90        25
     class 6       0.93      0.93      0.93        14
     class 7       0.75      1.00      0.86         6
     class 8       1.00      1.00      1.00         6
     class 9       0.89      1.00      0.94         8

    accuracy                           0.91       324
   macro avg       0.86      0.85      0.84       324
weighted avg       0.92      0.91      0.91       324



In [70]:
confusionMatrix = tf.math.confusion_matrix(labels= testLabelList, predictions=y_predicted_labels)

In [72]:
import seaborn as sn
plt.figure(figsize = (10, 7))
sn.heatmap(confusionMatrix, annot = True, fmt = 'd')
plt.xlabel('Predicted')
plt.ylabel('Actual')

Text(69.0, 0.5, 'Actual')